smbc-digital/StockportGovUK.NetStandard.Gateways

- src/StockportGovUK.NetStandard.Gateways.csproj
- src/VerintService/IVerintServiceGateway.cs
> fix: add AddCaseFormField to interface

- src/BookingService/BookingServiceGateway.cs
- src/BookingService/IBookingServiceGateway.cs
- src/StockportGovUK.NetStandard.Gateways.csproj
- test/StockportGovUK.NetStandard.Gateways.Tests.csproj
Added BookingServiceGateway with GetAvailability/NextAvailability/Reserve and Confirmation endpoints.
> feat(BookingServiceGateway)

- src/StockportGovUK.NetStandard.Gateways.csproj
- test/StockportGovUK.NetStandard.Gateways.Tests.csproj
update dep StockportGovUK.NetStandard.Models
> chore(project): update dep StockportGovUK.NetStandard.Models

- src/BookingService/BookingServiceGateway.cs
- src/BookingService/IBookingServiceGateway.cs
- src/StockportGovUK.NetStandard.Gateways.csproj
- test/StockportGovUK.NetStandard.Gateways.Tests.csproj
Release 5.4.0
Includes:
- BookingService gateway
- StockportGovUk.Model dependency to 1.1.7
> build: release 5.4.0

- src/StockportGovUK.NetStandard.Gateways.csproj
- test/StockportGovUK.NetStandard.Gateways.Tests.csproj
> major(Model): update major Models version

- src/StockportGovUK.NetStandard.Gateways.csproj
- test/StockportGovUK.NetStandard.Gateways.Tests.csproj
> chore(Book Site Inspection): update models

- src/StockportGovUK.NetStandard.Gateways.csproj
- test/StockportGovUK.NetStandard.Gateways.Tests.csproj
Updated Gateway deps StockportGovUK.NetStandard.Models to release 2.0.3
> deps(Packages): Updated Models package to 2.0.3

- src/StockportGovUK.NetStandard.Gateways.csproj
- test/StockportGovUK.NetStandard.Gateways.Tests.csproj
Features:
Updated deps StockportGovUK.NetStandard.Models to 2.0.3
> release: 6.0.2

- src/StockportGovUK.NetStandard.Gateways.csproj
- src/TrackAReport/ITrackAReportGateway.cs
- src/TrackAReport/TrackAReportGateway.cs
- test/StockportGovUK.NetStandard.Gateways.Tests.csproj
Add TrackAReport api to Gateways package for pre-release
> feat(track_a_report_D-4751): Add TrackAReport api

- src/StockportGovUK.NetStandard.Gateways.csproj
- test/StockportGovUK.NetStandard.Gateways.Tests.csproj
Updateing stockport.model package to 2.0.6
> chore(model) update model package

- src/TrackAReport/TrackAReportGateway.cs
Removed leading slash off api endpoint
> fix(track_a_report_D-4751): rm leading slash

- src/TrackAReport/TrackAReportGateway.cs
Removed leading slash from API endpoint
> fix(track_a_report_D-4751): rm leading slash (#88)

- src/StockportGovUK.NetStandard.Gateways.csproj
Version bump for Models and Gateways packages
> fix(track_a_report_D-4751): version bump

- src/Gateway.cs
- src/IGateway.cs
- src/StockportGovUK.NetStandard.Gateways.csproj
- src/TrackAReport/TrackAReportGateway.cs
- test/StockportGovUK.NetStandard.Gateways.Tests.csproj
Create post request to add tokens
> Added coder for PostAsync with additional headers

- src/StockportGovUK.NetStandard.Gateways.csproj
- src/WasteData/IWasteDataGateway.cs
- src/WasteData/WasteDataGateway.cs
- test/StockportGovUK.NetStandard.Gateways.Tests.csproj
- Updated waste Get to long
- Updated StockportGovUK.NetStandard.Models package to 3.0.0
> feat(waste): updated endpoint and packages

- src/BookingService/BookingServiceGateway.cs
- src/BookingService/IBookingServiceGateway.cs
Add cancellation to booking-service-gateway.
> Booking cancel

- src/StockportGovUK.NetStandard.Gateways.csproj
> patch: version bump

- src/BookingService/BookingServiceGateway.cs
- src/BookingService/IBookingServiceGateway.cs
- src/StockportGovUK.NetStandard.Gateways.csproj
- test/StockportGovUK.NetStandard.Gateways.Tests.csproj
Description
Add GetBbooking  endpoint
> feat(bookingGateway) Add GetBooking endpoint

- src/BookingService/BookingServiceGateway.cs
- src/StockportGovUK.NetStandard.Gateways.csproj
Fix for booking cancellation api route
> patch:  fix for booking cancellation route

- src/StockportGovUK.NetStandard.Gateways.csproj
Changed miss typing in project file
> Changed 8.6.o to 8.6.0

- src/StockportGovUK.NetStandard.Gateways.csproj
- src/VerintService/IVerintServiceGateway.cs
- src/VerintService/VerintServiceGateway.cs
Add AppendToCaseTitle to VerintService interface and service
> feat(verintGateway): add AppendToCaseTitle

- src/CivicaService/CivicaServiceGateway.cs
- src/CivicaService/ICivicaServicegateway.cs
- src/RevsBensService/IRevsBensServiceGateway.cs
- src/RevsBensService/RevsBensServiceGateway.cs
- src/StockportGovUK.NetStandard.Gateways.csproj
* feat(Civica + RevsBens): add endpoints for GetPerson
* chore(version): bump version
> feat(Civica + RevsBens): add new endpoints for GetPerson (#161)

- src/Enums/EBookingForeignReference.cs
- src/Models/Booking/Request/ConfirmationRequest.cs
- src/StockportGovUK.NetStandard.Gateways.csproj
Add ForeignReferences and FeePaid to Booking - ConfirmationRequest Model
Bump version
> chore(BookingConfirmationRequest): add new properties to Model

- src/Enums/EBookingForeignReference.cs
- src/StockportGovUK.NetStandard.Gateways.csproj
Add 'Reference' to list of Enums for BookingForeignReference for non-system references
> chore(EBookingForeignReference): add Reference

- src/BookingServiceAdmin/BookingServiceAdminGateway.cs
- src/BookingServiceAdmin/IBookingServiceAdminGateway.cs
- src/Gateway.cs
- src/Models/Verint/Address.cs
- src/Models/Verint/Case.cs
- src/StockportGovUK.NetStandard.Gateways.csproj
Add mapping between address types + helper method for adding case form fields with a value null check.
> Develop to Master

- src/StockportGovUK.NetStandard.Gateways.csproj
- src/UniformService/IUniformServiceGateway.cs
- src/UniformService/UniformServiceGateway.cs
new "check uniform case" end point added
> Uniform service

- src/BookingServiceAdmin/BookingAdminGateway.cs
- src/BookingServiceAdmin/IBookingServiceAdminGateway.cs
- src/Models/Booking/Booking.cs
- src/Models/Booking/Request/UpdateBookingStatus.cs
- src/StockportGovUK.NetStandard.Gateways.csproj
- Add endpoint to get status
- Add endpoint to update booking status id
> Booking status

- src/Enums/EMetaDataType.cs
- src/Models/Booking/Booking.cs
- src/Models/Booking/MetaDataCombined.cs
- src/Models/Booking/MetaDataField.cs
- src/StockportGovUK.NetStandard.Gateways.csproj
Add EMetaDataType
Add MetaDataCombined
Update MetaDataField
Update Booking
Bump version
> feat(Booking): Models for MetaData

- src/Models/Whitespace/Request/AddSiteServiceItemRoundScheduleRequest.cs
- src/Models/Whitespace/Response/SiteServiceScheduleResponse.cs
- src/Models/Whitespace/ServiceSchedule.cs
- src/PermiservService/IPermiservServiceGateway.cs
- src/PermiservService/PermiservServiceGateway.cs
- src/StockportGovUK.NetStandard.Gateways.csproj
- src/WhitespaceService/IWhitespaceServiceGateway.cs
- src/WhitespaceService/WhitespaceServiceGateway.cs
* Fake endpoints for load testing
* New Whitespace endpoints & models
> feat(Permiserv and Whitespace): new endpoints and models
